-- V1: fotografia do esquema que o Hibernate (ddl-auto=update) já vinha criando.
-- Em bancos que já existem, o Flyway faz "baseline" na versão 1 e PULA este script.
-- Em bancos novos, ele roda e cria tudo do zero.

CREATE TABLE tb_users (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name     VARCHAR(255),
    email    VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE tb_materias (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(100) NOT NULL,
    cor        VARCHAR(7)   NOT NULL,
    usuario_id BIGINT       NOT NULL REFERENCES tb_users (id)
);

CREATE TABLE tb_topicos (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome       VARCHAR(150) NOT NULL,
    concluido  BOOLEAN      NOT NULL DEFAULT FALSE,
    materia_id BIGINT       NOT NULL REFERENCES tb_materias (id)
);

CREATE TABLE tb_metas_estudo (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT      NOT NULL REFERENCES tb_users (id),
    materia_id BIGINT      NOT NULL REFERENCES tb_materias (id),
    dia        VARCHAR(10) NOT NULL,
    hora       VARCHAR(5)  NOT NULL,
    descricao  VARCHAR(200)
);

CREATE TABLE tb_sessoes_estudo (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT       NOT NULL REFERENCES tb_users (id),
    materia_id BIGINT       NOT NULL REFERENCES tb_materias (id),
    minutos    INTEGER      NOT NULL,
    anotacoes  VARCHAR(300),
    data       TIMESTAMP(6) NOT NULL
);
