-- V3: histórico do Ask IA (entidades Conversa e Mensagem do DER).

CREATE TABLE tb_conversas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id    BIGINT       NOT NULL REFERENCES tb_users (id),
    titulo        VARCHAR(100) NOT NULL,
    area          VARCHAR(20),
    criada_em     TIMESTAMP(6) NOT NULL,
    atualizada_em TIMESTAMP(6) NOT NULL
);

-- A listagem sempre filtra por usuário e ordena pela atividade mais recente.
CREATE INDEX idx_conversas_usuario_atualizada ON tb_conversas (usuario_id, atualizada_em DESC);

CREATE TABLE tb_mensagens (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    conversa_id         BIGINT       NOT NULL REFERENCES tb_conversas (id) ON DELETE CASCADE,
    autor               VARCHAR(10)  NOT NULL,   -- ALUNO | IA
    modo                VARCHAR(10),             -- EXPLICAR | RESOLVER | PLANO
    texto               TEXT,                    -- pergunta do aluno (nula nas mensagens da IA)
    topico              VARCHAR(100),            -- assunto identificado pela IA
    tente_voce_pergunta TEXT,
    tente_voce_resposta TEXT,
    criada_em           TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_mensagens_conversa ON tb_mensagens (conversa_id, id);

-- Passos numerados da resposta da IA (ElementCollection de MensagemModel).
CREATE TABLE tb_mensagem_passos (
    mensagem_id BIGINT       NOT NULL REFERENCES tb_mensagens (id) ON DELETE CASCADE,
    ordem       INTEGER      NOT NULL,
    titulo      VARCHAR(150) NOT NULL,
    conteudo    TEXT         NOT NULL,
    formula     VARCHAR(500),
    PRIMARY KEY (mensagem_id, ordem)
);
